spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/cronweb
    username: sa
    password:
    driver-class-name:  org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #테이블을 지우고 다시 생성
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        show_sql: true
        format_sql: true


  logging:
    level:
      org.hibernate.SQL: debug

